### ISSUE TITLE
Https requests

### ISSUE THREAD

**Issue by ThomasBucaioni** [tws-inc/gitea-group-sync#21]
Hello,
To change the `http` request by an `https` one, I changed the code in file `requests.go` from
```
cc := &http.Client{Timeout: time.Second * 2}
```
to
```
tr := &http.Transport{
        MaxIdleConns:       10,
        IdleConnTimeout:    30 * time.Second,
        DisableCompression: true,
}
cc := &http.Client{Transport: tr}
```
but I get the same response:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6cf9bf]

goroutine 1 [running]:
main.RequestGet(0xc000098d80, 0x1, 0x1, 0xc00001a03a, 0x26, 0xc00001a390, 0x30, 0x0, 0xc0000c8050, 0x7777c8, ...)
	/home/user/gitea-group-sync/requests.go:77 +0x27f
main.RequestOrganizationList(0xc000098d80, 0x1, 0x1, 0xc00001a03a, 0x26, 0xc00001a390, 0x30, 0x0, 0x7e, 0x1e, ...)
	/home/user/gitea-group-sync/requests.go:179 +0x67
main.mainJob()
	/home/user/gitea-group-sync/gitea-group-sync.go:240 +0x7d1
main.main()
	/home/user/gitea-group-sync/gitea-group-sync.go:60 +0x8a
exit status 2

```
Any idea what went wrong?

**Comment by ThomasBucaioni** [comment]
Localhost does, no worries
