### ISSUE TITLE
Gitea  1.22.4 can't add users to teams

### ISSUE THREAD

**Issue by gremlintomsk** [tws-inc/gitea-group-sync#23]
Hi, [another](https://github.com/gitea-group-sync/gitea-group-sync/issues/18) problem with gitea-group-sync after upgrade to Gitea 1.22.4 script not working(failing on deletion of users from group). I think they change API again.

```024/12/18 11:47:30 The gitea http://localhost:3000 has 1 users corresponding to team *** Teamid=31
2024/12/18 11:47:30 can be added users list []
2024/12/18 11:47:30 must be del users list []
2024/12/18 11:47:30 The LDAP my.ldap.local has 48 users corresponding to team ***
2024/12/18 11:47:30 The gitea http://localhost:3000 has 50 users corresponding to team *** Teamid=27
2024/12/18 11:47:30 can be added users list []
2024/12/18 11:47:30 must be del users list [{223 *** user1} {180 *** user2}]
CheckStatusCode gitea apiKeys connection error: Client error
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.DelUsersFromTeam(0xc0001223e0, 0x2, 0x2, 0xc000138380, 0x15, 0xc0000c31d0, 0x2a, 0x0, 0xc000098370, 0x2, ...)
	/opt/gitea-group-sync/gitea-group-sync.go:49 +0x2ed
main.mainJob()
	/opt/gitea-group-sync/gitea-group-sync.go:300 +0x12dd
main.main()
	/opt/gitea-group-sync/gitea-group-sync.go:60 +0x8a
exit status 2
```
Script release version 0.2

**Comment by localleon** [comment]
Open to PRs ;-) We currently don't really activly maintain this project

**Comment by gremlintomsk** [comment]
Problem was in API in my configuration. On api/v1/users/search response was:

> {
  "errors": null,
  "message": "The target couldn't be found.",
  "url": "https://gitea/api/swagger"
}

I rewrote script to use users/{username} and it's works again
